/// A flexible way to handle config

use serde::Deserialize;
use struct_patch::Patch;


// Note: The ConfigPatch is generated by Patch derive
#[derive(Debug, Default, Deserialize, PartialEq, Patch)]
// The dervice will apply to the ConfigPatch
#[patch(attribute(derive(Default, Debug, Deserialize, PartialEq)))]
pub struct Config {
    pub name: String,
    pub verb: String,
    #[patch(nesting)]
    pub nested: NestedConfig,
}

// Note: The NestedConfigPatch is generated by Patch derive
#[derive(Debug, Deserialize, PartialEq, Patch)]
// The dervice will apply to the NestedConfigPatch
#[patch(attribute(derive(Default, Debug, Deserialize, PartialEq)))]
pub struct NestedConfig {
    pub inner: String,
}

impl Default for NestedConfig {
    fn default() -> NestedConfig {
        NestedConfig {
            inner: "Things".to_string()
        }
    }
}


#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    /// This test case demo how we can from a defaul config then patch with 
    /// toml, then with yaml and then with envvar
    ///
    /// You can easy to swap any config layers with different crate and tools
    fn config_with_patch() {
        let mut config = Config::default();

        assert_eq!(config.name, "");
        assert_eq!(config.verb, "");
        assert_eq!(config.nested.inner, "Things");

        let config_patch_from_yaml =  serde_saphyr::from_str::<ConfigPatch>(r#"name: name
verb: do
nested: ~
"#).unwrap();
        config.apply(config_patch_from_yaml);

        assert_eq!(config.name, "name");
        assert_eq!(config.verb, "do");
        assert_eq!(config.nested.inner, "Things");
        
        let config_patch_from_toml = toml::from_str::<ConfigPatch>(r#"
            [nested]
            inner = "Something"
            "#).unwrap();
        
        config.apply(config_patch_from_toml);

        assert_eq!(config.name, "name");
        assert_eq!(config.verb, "do");
        assert_eq!(config.nested.inner, "Something");

        std::env::set_var("MY_NAME", "Antonio");
        std::env::set_var("MY_NESTED__INNER", "SomethingGood");

        let config_patch_from_envar: ConfigPatch = envious::Config::default().with_prefix("MY_").build_from_env().expect("Could not deserialize from env");
        config.apply(config_patch_from_envar);

        assert_eq!(config.name, "Antonio");
        assert_eq!(config.verb, "do");
        assert_eq!(config.nested.inner, "SomethingGood");
    }
}
